apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-cm
data:
  locustfile.py: |
    from locust import HttpUser, task, between, tag
    import json
    import random
    
    class LoadSimulator(HttpUser):
        wait_time = between(0.1, 0.5)
        json_headers = {'Content-Type': 'application/json', 'Accept': 'application/json'}
        
        @task
        @tag('getCache')
        def get_cache(self):
            num = random.randint(1, 1000000)
            cacheId = 'cdd7cacd-8e0a-4372-8ceb-' + str(num).zfill(12)
            self.client.get(f"/api/cache/{cacheId}", name="/api/cache/?")
        
        @task
        @tag('getCacheWithTTL')
        def get_cache_ttl(self):
            num = random.randint(1, 1000000)
            cacheId = 'cdd7cacd-8e0a-4372-8ceb-' + str(num).zfill(12)
            self.client.get(f"/api/cache/alt/{cacheId}?ttl=30", name="/api/cache/alt/?")
        
        @task
        @tag('saveCache')
        def post_cache(self):
            json_data = {
                'deviceId': "deviceId",
                'mediaId': "mediaId",
                'status': "status"
            }
            self.client.post(f"/api/cache?ttl=60", data=json.dumps(json_data), headers=LoadSimulator.json_headers, name="/api/cache/?")
        
        # @task
        @tag('deviceTracker2')
        def patch_device_tracker2(self):
            num = random.randint(1, 11000)
            num2 = random.randint(1, 60)
            deviceId = 'cdd7cacd-8e0a-4372-8ceb-' + str(num).zfill(12)
            mediaId = '48d1c2c2-0d83-43d9-' + str(num2).zfill(4) + '-' + str(num).zfill(12)
            status = 'MOD-' + str(random.randint(0, 3))
            jsond = {
                'deviceId': deviceId,
                'mediaId': mediaId,
                'status': status
            }
            self.client.patch(f"/api/tracker", data=json.dumps(jsond), headers=json_headers)
