server:
  http2.enabled: ${SERVER_HTTP2_ENABLED:true}
  compression.enabled: ${SERVER_COMPRESSION_ENABLED:true}
  forward-headers-strategy: ${SERVER_FORWARD_HEADER_STRATEGY:native}
  tomcat:
    threads:
      max: ${TOMCAT_THREADS_MAX:250} # bump from 200
      min-spare: ${TOMCAT_THREADS_MIN_SPARE:10}
    max-connections: 8192

management:
  endpoint:
    health.probes.enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus