spring.ssl.bundle.jks:
  server-cert:
    reload-on-update: true
    keystore:
      location: ${CERT_PATH}/keystore.jks
      password: ${PASSWORD}
      type: JKS
    truststore:
      location: ${CERT_PATH}/truststore.jks
      password: ${PASSWORD}
      type: JKS

server:
  port: ${SEVER_PORT:8443}
  ssl.bundle: ${SERVER_SSL_BUNDLE:server-cert}