#
#
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: cache-app-config
  namespace: default
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  DATASOURCE_URL: "jdbc:yugabytedb://10.204.0.20:5433/yugabyte"
  HIKARI_IDLE_TIMEOUT: "0"
  HIKARI_MINIMUM_IDLE: "10"
  HIKARI_MAXIMUM_POOL_SIZE: "10"
  HIKARI_MAX_LIFETIME: "1800000"
  HIKARI_KEEPALIVE_TIME: "600000"
  HIKARI_VALIDATION_TIMEOUT: "60000"
  HIKARI_LOG_LEVEL: "DEBUG"
  HIKARI_CONFIG_LOG_LEVEL: "DEBUG"
  YSQL_CURRENT_SCHEMA: "ysql_cache"
  YSQL_CONNECT_TIMEOUT: "15"
  YSQL_SOCKET_TIMEOUT: "10"
  YSQL_PREPARE_THRESHOLD: "1"
  YSQL_OPTIONS: "-c statement_timeout=8s"
  YSQL_ADDITIONAL_ENDPOINTS: "10.204.0.15:5433,10.204.0.34:5433"
  YSQL_LOAD_BALANCE: "true"
  YSQL_TOPOLOGY_KEYS: "gcp.us-east1.*:1"
  YSQL_DRIVER_LOG_LEVEL: "DEBUG"
  YSQL_PGCONNECTION_LOG_LEVEL: "INFO"